services:
  - type: web
    name: simple-store-cashfree-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: CASHFREE_APP_ID
        sync: false
      - key: CASHFREE_SECRET_KEY
        sync: false
      - key: CASHFREE_ENV
        value: sandbox
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
